#Importamos la imagen base con python

FROM python:3.12-slim

#Se crea carpeta de trabajo del contenedor

WORKDIR /app

#Se copia los requerimientos del servidor

COPY requirements.txt .

#Instalamos los requerimientos

RUN pip install --no-cache-dir -r requirements.txt

#Copiar el código de API

COPY ./app ./app

#Se expone el puerto para acceder a la API

EXPOSE 5000

#Comando para ejecutar la API

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]

#0.0.0.0 --> LocalHost
#Puerto 5000 --> Puerto donde se ejecuta la API






